[book]
authors = ["Kyosuke Fujimoto"]
language = "zh-TW"
src = "src"
title = "ysgit"
description = "ysgit 文件（serie fork）"

[output.html]
git-repository-url = "https://github.com/YSzEthan/serie-ys"
site-url = "/serie-ys/"
default-theme = "rust"
